# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f15e0ec895ad7a0e4878b2b9dcab5ba706436e5ba0965370a51ae9410d4db0be45bf52b26022e0683d4ad6283545178ddf1baa2e42897cd45e30e7cfb2b1e6

test:
  secret_key_base: 4bc2fabe98dc1c2c82607a1d0e074ab2caf3e11da9b4460c6e7bb24fa687d97be0f763747ec6feb313d860da0cd08b40e59bccfbe1ddae4d5dab68a6c3badaca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
